// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroup = "groups"

// Group mapped from table <groups>
type Group struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GroupName string `gorm:"column:group_name;not null" json:"group_name"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
