// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSongsVerse = "songs_verses"

// SongsVerse mapped from table <songs_verses>
type SongsVerse struct {
	SongID int32  `gorm:"column:song_id;not null" json:"song_id"`
	Verses string `gorm:"column:verses;not null" json:"verses"`
	Tsv    string `gorm:"column:tsv" json:"tsv"`
}

// TableName SongsVerse's table name
func (*SongsVerse) TableName() string {
	return TableNameSongsVerse
}
